parameters:
  project: ''
  vmImage: ''
  buildConfiguration: ''
  runtime: ''
  appVersion: ''
  environment: ''

jobs:
  - deployment: DeployWebApp
    # displayName: "Deploy to ${{ parameters.environment }}"
    pool:
      name: "Azure Pipelines"
      vmImage: ${{ parameters.vmImage }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            # - download: current
            #   artifact: ${{ parameters.appVersion }}
            - script: ls $(Build.ArtifactStagingDirectory)
            - script: echo Deployed to ${{ parameters.environment }}
            # - task: AzureRmWebAppDeployment@4
            #   inputs:
            #     ConnectionType: "$(ConnectionType)"
            #     azureSubscription: "$(azureSubscription)"
            #     appType: "$(appType)"
            #     WebAppName: "$(WebAppName)"
            #     packageForLinux: "$(Pipeline.Workspace)/**/*.zip"
            #     RuntimeStack: "$(RuntimeStack)"
